env:
  es6: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

rules:
  react/react-in-jsx-scope: false

settings:
  react:
    version: '16'

globals:
  webpack: readonly
